'use strict';
let money = 100000;
console.log (typeof money);
const income = 'фриланс';
console.log (typeof income);
let addExpenses = 'Курсы Отпуск Проездной';
console.log (addExpenses.toLowerCase());
console.log (addExpenses.length);
console.log (addExpenses.toLowerCase().split(" "));
let deposit = true;
console.log (typeof deposit);
let mission = 500000;
let period = 8;
console.log ("Период равен " + period + " месяцев");
console.log ("Цель заработать " + mission + " рублей/долларов/гривен/юани");
let budgetDay  = money / 30;
console.log (budgetDay);
alert ("привет, мир");
console.log ('привет');
